/**
 * AUTO-GENERATED by spec-to-e2e.js — 2026-06-19T03:18:41.848Z
 * 来源: Product-Spec.md 用户场景
 * 
 * ⚠ 此文件为骨架代码。选择器和断言需根据实际 UI 调整。
 * 运行: npx playwright test spec-generated.spec.ts
 */
import { test, expect, _electron as electron } from '@playwright/test';
import path from 'path';

const EP = path.join(__dirname, '..', 'node_modules', 'electron', 'dist', 'electron.exe');
const MAIN = path.join(__dirname, '..', 'out', 'main', 'index.js');


// 测试数据工厂: 预填充 Skill/项目/章节，让条件分支场景可触发
const { setupFixtures, cleanupFixtures } = require('./test-fixtures');

test.describe('Spec 用户场景验证 (自动生成)', () => {
  let app, page;

  test.beforeAll(async () => {
    // 注入测试数据（Skill + 项目 + 章节）
    setupFixtures(__dirname);
    app = await electron.launch({ executablePath: EP, args: [MAIN] });
page = await app.firstWindow();
    await page.waitForLoadState('load').catch(() => {});
    await page.waitForTimeout(3000);
    const txt = await page.locator('body').innerText().catch(() => '');
    expect(txt.length).toBeGreaterThan(0);
  }, 35000);

  test.afterAll(async () => {
    try { await app.close(); await app.process().kill(); } catch (e) {}
    cleanupFixtures(__dirname);
  });

  // ═══ Spec: 交互路径: [↗ 导出] → 选择导出路径 → 系统打包 Skill 为完整文件夹 [🟢🟢] ═══
  test('[1] [↗ 导出]', async () => {
    // 触发: [↗ 导出]
    // 预期: 选择导出路径 → 系统打包 Skill 为完整文件夹
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证 Skill 卡片/项目列表
    const cards = page.locator('[data-testid="skill-card"], [data-testid="project-row"]');
    const cardCount = await cards.count();
    expect(cardCount).toBeGreaterThanOrEqual(0);
    if (cardCount > 0) await expect(cards.first()).toBeVisible();
  });

  // ═══ Spec: 交互路径: `chapter_index.md` → 打开 Markdown 编辑器模式（可编辑原始内容） [🟡] ═══
  test('[2] `chapter_index.md`', async () => {
    // 触发: `chapter_index.md`
    // 预期: 打开 Markdown 编辑器模式（可编辑原始内容）
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证页面有基本内容
    await page.waitForTimeout(500);
    const bodyText = await page.locator('body').innerText().catch(() => '');
    expect(bodyText.length).toBeGreaterThan(10);
  });

  // ═══ Spec: 交互路径: 任一章节行 → 编辑区新建标签页，加载对应 `chapters/Chapter-XX.md` 文件（Markdown 编辑模式） [🟢🟢] ═══
  test('[3] 任一章节行', async () => {
    // 触发: 任一章节行
    // 预期: 编辑区新建标签页，加载对应 `chapters/Chapter-XX.md` 文件（Markdown 编辑模式）
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证标签页
    const tabs = page.locator('[data-testid="tab"]');
    const tabCount = await tabs.count();
    expect(tabCount).toBeGreaterThanOrEqual(0);
    if (tabCount > 0) await expect(tabs.first()).toBeVisible();
  });

  // ═══ Spec: 交互路径: 左侧阶段卡片 → AI 自动发送预设引导指令 / 底部输入框手动输入 [🟢🟢] ═══
  test('[4] 左侧阶段卡片', async () => {
    // 触发: 左侧阶段卡片
    // 预期: AI 自动发送预设引导指令 / 底部输入框手动输入
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证 AI 对话区
    const chatBody = page.locator('[data-testid="chat-body"]').first();
    const chatVisible = await chatBody.isVisible({ timeout: 3000 }).catch(() => false);
    if (chatVisible) {
      await expect(chatBody).toBeVisible();
      const msgs = page.locator('[data-testid="ai-message"], [data-testid="user-message"]');
      expect(await msgs.count()).toBeGreaterThanOrEqual(0);
    }
  });

  // ═══ Spec: 交互路径: 展开搜索框，输入关键词 → 高亮匹配的对话块 + 上下箭头跳转到上一个/下一个匹配项 [🟢🟢] ═══
  test('[5] 展开搜索框，输入关键词', async () => {
    // 触发: 展开搜索框，输入关键词
    // 预期: 高亮匹配的对话块 + 上下箭头跳转到上一个/下一个匹配项
    
    const input = page.locator('[data-testid="chat-input"], input:not([type="hidden"]), textarea').first();
    if (await input.isVisible().catch(() => false)) await input.fill('测试输入');

    // 验证 AI 对话区
    const chatBody = page.locator('[data-testid="chat-body"]').first();
    const chatVisible = await chatBody.isVisible({ timeout: 3000 }).catch(() => false);
    if (chatVisible) {
      await expect(chatBody).toBeVisible();
      const msgs = page.locator('[data-testid="ai-message"], [data-testid="user-message"]');
      expect(await msgs.count()).toBeGreaterThanOrEqual(0);
    }
  });

  // ═══ Spec: 交互路径: 同一阶段卡片 → 忽略点击，对话区显示系统消息"正在生成中，请等待当前任务完成" [🟢🟢] ═══
  test('[6] 同一阶段卡片', async () => {
    // 触发: 同一阶段卡片
    // 预期: 忽略点击，对话区显示系统消息"正在生成中，请等待当前任务完成"
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证 AI 对话区
    const chatBody = page.locator('[data-testid="chat-body"]').first();
    const chatVisible = await chatBody.isVisible({ timeout: 3000 }).catch(() => false);
    if (chatVisible) {
      await expect(chatBody).toBeVisible();
      const msgs = page.locator('[data-testid="ai-message"], [data-testid="user-message"]');
      expect(await msgs.count()).toBeGreaterThanOrEqual(0);
    }
  });

  // ═══ Spec: 交互路径: 其他阶段卡片 → 忽略点击，对话区显示系统消息"当前任务完成后，再点击阶段卡片开始新任务" [🟢🟢] ═══
  test('[7] 其他阶段卡片', async () => {
    // 触发: 其他阶段卡片
    // 预期: 忽略点击，对话区显示系统消息"当前任务完成后，再点击阶段卡片开始新任务"
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证 AI 对话区
    const chatBody = page.locator('[data-testid="chat-body"]').first();
    const chatVisible = await chatBody.isVisible({ timeout: 3000 }).catch(() => false);
    if (chatVisible) {
      await expect(chatBody).toBeVisible();
      const msgs = page.locator('[data-testid="ai-message"], [data-testid="user-message"]');
      expect(await msgs.count()).toBeGreaterThanOrEqual(0);
    }
  });

  // ═══ Spec: 交互路径: 输入框有内容时 → 发送按钮恢复正常，可点击发送 [🟢🟢] ═══
  test('[8] 输入框有内容时', async () => {
    // 触发: 输入框有内容时
    // 预期: 发送按钮恢复正常，可点击发送
    
    const input = page.locator('[data-testid="chat-input"], input:not([type="hidden"]), textarea').first();
    if (await input.isVisible().catch(() => false)) await input.fill('测试输入');

    // 验证 AI 对话区
    const chatBody = page.locator('[data-testid="chat-body"]').first();
    const chatVisible = await chatBody.isVisible({ timeout: 3000 }).catch(() => false);
    if (chatVisible) {
      await expect(chatBody).toBeVisible();
      const msgs = page.locator('[data-testid="ai-message"], [data-testid="user-message"]');
      expect(await msgs.count()).toBeGreaterThanOrEqual(0);
    }
  });

  // ═══ Spec: 交互路径: [✏️ 手动接管] 中断 AI 后 → 阶段状态从 ⟳ 回退到 ⏹（文件保留已生成的半成品内容） [🟢🟢] ═══
  test('[9] [✏️ 手动接管] 中断 AI 后', async () => {
    // 触发: [✏️ 手动接管] 中断 AI 后
    // 预期: 阶段状态从 ⟳ 回退到 ⏹（文件保留已生成的半成品内容）
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证 AI 对话区
    const chatBody = page.locator('[data-testid="chat-body"]').first();
    const chatVisible = await chatBody.isVisible({ timeout: 3000 }).catch(() => false);
    if (chatVisible) {
      await expect(chatBody).toBeVisible();
      const msgs = page.locator('[data-testid="ai-message"], [data-testid="user-message"]');
      expect(await msgs.count()).toBeGreaterThanOrEqual(0);
    }
  });

  // ═══ Spec: 交互路径: → 若该文件已在编辑区有打开的标签页 → 切换到已有标签页并聚焦 [🟢🟢] ═══
  test('[10] → 若该文件已在编辑区有打开的标签页', async () => {
    // 触发: → 若该文件已在编辑区有打开的标签页
    // 预期: 切换到已有标签页并聚焦
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证标签页
    const tabs = page.locator('[data-testid="tab"]');
    const tabCount = await tabs.count();
    expect(tabCount).toBeGreaterThanOrEqual(0);
    if (tabCount > 0) await expect(tabs.first()).toBeVisible();
  });

  // ═══ Spec: 交互路径: 关闭按钮（✕） → 强制保存所有打开的标签页（不论自动保存间隔）→ 退出应用 [🟢🟢] ═══
  test('[11] 关闭按钮（✕）', async () => {
    // 触发: 关闭按钮（✕）
    // 预期: 强制保存所有打开的标签页（不论自动保存间隔）→ 退出应用
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证标签页
    const tabs = page.locator('[data-testid="tab"]');
    const tabCount = await tabs.count();
    expect(tabCount).toBeGreaterThanOrEqual(0);
    if (tabCount > 0) await expect(tabs.first()).toBeVisible();
  });

  // ═══ Spec: 交互路径: 左侧阶段卡片 → 预设指令自动填入并发送 + 对话区自动添加阶段分隔线 [🟢🟢] ═══
  test('[12] 左侧阶段卡片', async () => {
    // 触发: 左侧阶段卡片
    // 预期: 预设指令自动填入并发送 + 对话区自动添加阶段分隔线
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证 AI 对话区
    const chatBody = page.locator('[data-testid="chat-body"]').first();
    const chatVisible = await chatBody.isVisible({ timeout: 3000 }).catch(() => false);
    if (chatVisible) {
      await expect(chatBody).toBeVisible();
      const msgs = page.locator('[data-testid="ai-message"], [data-testid="user-message"]');
      expect(await msgs.count()).toBeGreaterThanOrEqual(0);
    }
  });

  // ═══ Spec: 交互路径: 顶部导航进入 [⚙ 设置 → API 配置] → 添加 Claude + DeepSeek → 填入 Key → [🔍] 拉取模型列表 → 保存 [🟢🟢] ═══
  test('[13] 顶部导航进入 [⚙ 设置', async () => {
    // 触发: 顶部导航进入 [⚙ 设置
    // 预期: API 配置] → 添加 Claude + DeepSeek → 填入 Key → [🔍] 拉取模型列表 → 保存
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证页面/视图切换
    await page.waitForTimeout(800);
    const bodyText = await page.locator('body').innerText().catch(() => '');
    expect(bodyText).toMatch(/API|模型|配置/);
  });

  // ═══ Spec: 交互路径: [+ 新建项目] → 输入"霸总契约新娘" → 创建 [🟢🟢] ═══
  test('[14] [+ 新建项目]', async () => {
    // 触发: [+ 新建项目]
    // 预期: 输入"霸总契约新娘" → 创建
    
    const btn = page.locator('[data-testid="btn-new-project"]').first();
    if (await btn.isVisible().catch(() => false)) await btn.click();

    // 验证弹窗出现
    const modal = page.locator('[data-testid="modal-overlay"]').first();
    const modalVisible = await modal.isVisible({ timeout: 3000 }).catch(() => false);
    if (modalVisible) {
      await expect(page.locator('[data-testid="modal-title"]').first()).toBeVisible();
      const confirmBtn = page.locator('[data-testid="modal-confirm"]').first();
      await expect(confirmBtn).toBeVisible();
    }
  });

  // ═══ Spec: 交互路径: "第一章 · 婚礼上的陌生人" → 编辑区打开 Chapter-01.md 标签页 [🟢🟢] ═══
  test('[15] 第一章 · 婚礼上的陌生人', async () => {
    // 触发: "第一章 · 婚礼上的陌生人"
    // 预期: 编辑区打开 Chapter-01.md 标签页
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证标签页
    const tabs = page.locator('[data-testid="tab"]');
    const tabCount = await tabs.count();
    expect(tabCount).toBeGreaterThanOrEqual(0);
    if (tabCount > 0) await expect(tabs.first()).toBeVisible();
  });

  // ═══ Spec: 交互路径: "暗恋十年成真"项目 → 进入工作台 [🟢🟢] ═══
  test('[16] 暗恋十年成真项目', async () => {
    // 触发: "暗恋十年成真"项目
    // 预期: 进入工作台
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证页面/视图切换
    await page.waitForTimeout(800);
    const bodyText = await page.locator('body').innerText().catch(() => '');
    expect(bodyText.length).toBeGreaterThan(20);
  });

  // ═══ Spec: 交互路径: "悬疑推理"Skill（展开） → "现言"Skill 自动收缩 [🟢🟢] ═══
  test('[17] 悬疑推理Skill（展开）', async () => {
    // 触发: "悬疑推理"Skill（展开）
    // 预期: "现言"Skill 自动收缩
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证 Skill 卡片/项目列表
    const cards = page.locator('[data-testid="skill-card"], [data-testid="project-row"]');
    const cardCount = await cards.count();
    expect(cardCount).toBeGreaterThanOrEqual(0);
    if (cardCount > 0) await expect(cards.first()).toBeVisible();
  });

  // ═══ Spec: 交互路径: "密室杀人案"项目 → 进入工作台 [🟢🟢] ═══
  test('[18] 密室杀人案项目', async () => {
    // 触发: "密室杀人案"项目
    // 预期: 进入工作台
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证页面/视图切换
    await page.waitForTimeout(800);
    const bodyText = await page.locator('body').innerText().catch(() => '');
    expect(bodyText.length).toBeGreaterThan(20);
  });

  // ═══ Spec: 用户行为: 点击 [↗ 导出] → 选择导出路径 → 系统打包 Skill 为完整文件夹 [🟢🟢] ═══
  test('[19] 点击 [↗ 导出]', async () => {
    // 触发: 点击 [↗ 导出]
    // 预期: 选择导出路径 → 系统打包 Skill 为完整文件夹
    
    const btn = page.locator('[data-testid="stage-card"], [data-testid="chapter-row"], [data-testid="tab"]').filter({ hasText: /[↗ 导出]/ }).first();
    if (await btn.isVisible().catch(() => false)) await btn.click();

    // 验证 Skill 卡片/项目列表
    const cards = page.locator('[data-testid="skill-card"], [data-testid="project-row"]');
    const cardCount = await cards.count();
    expect(cardCount).toBeGreaterThanOrEqual(0);
    if (cardCount > 0) await expect(cards.first()).toBeVisible();
  });

  // ═══ Spec: 用户行为: 删除某 Skill 时，若该 Skill 下还有未删除的项目 → 弹出警告"该 Skill 下有 N 个项目，删除 Skill 后这些项目将失去创作方法论指导，但项目文件不会被删除 [🟢🟢] ═══
  test('[20] 删除某 Skill 时，若该 Skill 下还有未删除的项目', async () => {
    // 触发: 删除某 Skill 时，若该 Skill 下还有未删除的项目
    // 预期: 弹出警告"该 Skill 下有 N 个项目，删除 Skill 后这些项目将失去创作方法论指导，但项目文件不会被删除
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证弹窗出现
    const modal = page.locator('[data-testid="modal-overlay"]').first();
    const modalVisible = await modal.isVisible({ timeout: 3000 }).catch(() => false);
    if (modalVisible) {
      await expect(page.locator('[data-testid="modal-title"]').first()).toBeVisible();
      const confirmBtn = page.locator('[data-testid="modal-confirm"]').first();
      await expect(confirmBtn).toBeVisible();
    }
  });

  // ═══ Spec: 用户行为: 右键项目名 → 弹出菜单（打开/重命名/置顶/移入回收站/彻底删除） [🟢🟢] ═══
  test('[21] 右键项目名', async () => {
    // 触发: 右键项目名
    // 预期: 弹出菜单（打开/重命名/置顶/移入回收站/彻底删除）
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证弹窗出现
    const modal = page.locator('[data-testid="modal-overlay"]').first();
    const modalVisible = await modal.isVisible({ timeout: 3000 }).catch(() => false);
    if (modalVisible) {
      await expect(page.locator('[data-testid="modal-title"]').first()).toBeVisible();
      const confirmBtn = page.locator('[data-testid="modal-confirm"]').first();
      await expect(confirmBtn).toBeVisible();
    }
  });

  // ═══ Spec: 用户行为: 发起重命名 → IPC 调用 `project:rename` → 成功 → 更新 UI（乐观更新先行，失败时回退）→ 失败（权限不足/文件名冲突）→ 显示内联错误提示，恢复原 [🟢🟢] ═══
  test('[22] 发起重命名', async () => {
    // 触发: 发起重命名
    // 预期: IPC 调用 `project:rename` → 成功 → 更新 UI（乐观更新先行，失败时回退）→ 失败（权限不足/文件名冲突）→ 显示内联错误提示，恢复原
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证 Toast 消息
    const toast = page.locator('[data-testid="toast-message"]').first();
    const toastVisible = await toast.isVisible({ timeout: 3000 }).catch(() => false);
    if (toastVisible) await expect(toast).toBeVisible();
  });

  // ═══ Spec: 用户行为: 可双击标签名重命名。新文件纳入文件树显示。若项目目录已存在 `未命名.md` → 自动命名为 `未命名-1.md`、`未命名-2.md`... [🟢🟢] ═══
  test('[23] 可双击标签名重命名。新文件纳入文件树显示。若项目目录已存在 `未命名.md`', async () => {
    // 触发: 可双击标签名重命名。新文件纳入文件树显示。若项目目录已存在 `未命名.md`
    // 预期: 自动命名为 `未命名-1.md`、`未命名-2.md`...
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证标签页
    const tabs = page.locator('[data-testid="tab"]');
    const tabCount = await tabs.count();
    expect(tabCount).toBeGreaterThanOrEqual(0);
    if (tabCount > 0) await expect(tabs.first()).toBeVisible();
  });

  // ═══ Spec: 用户行为: 点击应用 → 替换编辑区中的原选中文本 [🟡] ═══
  test('[24] 点击应用', async () => {
    // 触发: 点击应用
    // 预期: 替换编辑区中的原选中文本
    
    const btn = page.locator('[data-testid="stage-card"], [data-testid="chapter-row"], [data-testid="tab"]').filter({ hasText: /应用/ }).first();
    if (await btn.isVisible().catch(() => false)) await btn.click();

    // 验证页面有基本内容
    await page.waitForTimeout(500);
    const bodyText = await page.locator('body').innerText().catch(() => '');
    expect(bodyText.length).toBeGreaterThan(10);
  });

  // ═══ Spec: 用户行为: 在预览期间修改了编辑区内容 → 点击应用时提示"编辑区内容已变更，应用预览将覆盖当前选中的文本" [🟢🟢] ═══
  test('[25] 在预览期间修改了编辑区内容', async () => {
    // 触发: 在预览期间修改了编辑区内容
    // 预期: 点击应用时提示"编辑区内容已变更，应用预览将覆盖当前选中的文本"
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证输入区域可用
    const inputArea = page.locator('[data-testid="chat-input"], input:not([type="hidden"]), textarea, [contenteditable="true"]').first();
    const iaVisible = await inputArea.isVisible({ timeout: 3000 }).catch(() => false);
    if (iaVisible) {
      await expect(inputArea).toBeVisible();
      await expect(inputArea).toBeEnabled();
    }
  });

  // ═══ Spec: 用户行为: 点击 [✏️ 手动接管] 中断 AI 后 → 阶段状态从 ⟳ 回退到 ⏹（文件保留已生成的半成品内容） [🟢🟢] ═══
  test('[26] 点击 [✏️ 手动接管] 中断 AI 后', async () => {
    // 触发: 点击 [✏️ 手动接管] 中断 AI 后
    // 预期: 阶段状态从 ⟳ 回退到 ⏹（文件保留已生成的半成品内容）
    
    const btn = page.locator('[data-testid="stage-card"], [data-testid="chapter-row"], [data-testid="tab"]').filter({ hasText: /[✏️ 手动接管] 中断 AI/ }).first();
    if (await btn.isVisible().catch(() => false)) await btn.click();

    // 验证 AI 对话区
    const chatBody = page.locator('[data-testid="chat-body"]').first();
    const chatVisible = await chatBody.isVisible({ timeout: 3000 }).catch(() => false);
    if (chatVisible) {
      await expect(chatBody).toBeVisible();
      const msgs = page.locator('[data-testid="ai-message"], [data-testid="user-message"]');
      expect(await msgs.count()).toBeGreaterThanOrEqual(0);
    }
  });

  // ═══ Spec: 用户行为: 关闭应用 → 重启后阶段状态根据文件内容重新判定（文件有内容→✅，文件为空→⏹，不会卡在 ⟳） [🟢] ═══
  test('[27] 关闭应用', async () => {
    // 触发: 关闭应用
    // 预期: 重启后阶段状态根据文件内容重新判定（文件有内容→✅，文件为空→⏹，不会卡在 ⟳）
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证状态变化
    await page.waitForTimeout(500);
    const bodyText = await page.locator('body').innerText().catch(() => '');
    expect(bodyText.length).toBeGreaterThan(20);
  });

  // ═══ Spec: 用户行为: 点击关闭 → 弹出确认"AI 正在生成内容，关闭应用将中断生成 [🟢🟢] ═══
  test('[28] 点击关闭', async () => {
    // 触发: 点击关闭
    // 预期: 弹出确认"AI 正在生成内容，关闭应用将中断生成
    
    const btn = page.locator('[data-testid="stage-card"], [data-testid="chapter-row"], [data-testid="tab"]').filter({ hasText: /关闭/ }).first();
    if (await btn.isVisible().catch(() => false)) await btn.click();

    // 验证弹窗出现
    const modal = page.locator('[data-testid="modal-overlay"]').first();
    const modalVisible = await modal.isVisible({ timeout: 3000 }).catch(() => false);
    if (modalVisible) {
      await expect(page.locator('[data-testid="modal-title"]').first()).toBeVisible();
      const confirmBtn = page.locator('[data-testid="modal-confirm"]').first();
      await expect(confirmBtn).toBeVisible();
    }
  });

  // ═══ Spec: 用户行为: 手动清空文件内容 | → ⏹（保持） | → ⏹（AI 被中断时回退） | → ⏹ | [🟢🟢] ═══
  test('[29] 手动清空文件内容 |', async () => {
    // 触发: 手动清空文件内容 |
    // 预期: ⏹（保持） | → ⏹（AI 被中断时回退） | → ⏹ |
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证弹窗出现
    const modal = page.locator('[data-testid="modal-overlay"]').first();
    const modalVisible = await modal.isVisible({ timeout: 3000 }).catch(() => false);
    if (modalVisible) {
      await expect(page.locator('[data-testid="modal-title"]').first()).toBeVisible();
      const confirmBtn = page.locator('[data-testid="modal-confirm"]').first();
      await expect(confirmBtn).toBeVisible();
    }
  });

  // ═══ Spec: 用户行为: 从文件树手动编辑并保存 | → ✅（若内容非空） | → ✅（AI 完成后自动判定） | → ✅（保持） | [🟢🟢] ═══
  test('[30] 从文件树手动编辑并保存 |', async () => {
    // 触发: 从文件树手动编辑并保存 |
    // 预期: ✅（若内容非空） | → ✅（AI 完成后自动判定） | → ✅（保持） |
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证 AI 对话区
    const chatBody = page.locator('[data-testid="chat-body"]').first();
    const chatVisible = await chatBody.isVisible({ timeout: 3000 }).catch(() => false);
    if (chatVisible) {
      await expect(chatBody).toBeVisible();
      const msgs = page.locator('[data-testid="ai-message"], [data-testid="user-message"]');
      expect(await msgs.count()).toBeGreaterThanOrEqual(0);
    }
  });

  // ═══ Spec: 用户行为: 切换模型 → 检测引擎是否变化 [🟡] ═══
  test('[31] 切换模型', async () => {
    // 触发: 切换模型
    // 预期: 检测引擎是否变化
    
    const btn = page.locator('[data-testid="stage-card"], [data-testid="chapter-row"], [data-testid="tab"]').filter({ hasText: /模型/ }).first();
    if (await btn.isVisible().catch(() => false)) await btn.click();

    // 验证页面有基本内容
    await page.waitForTimeout(500);
    const bodyText = await page.locator('body').innerText().catch(() => '');
    expect(bodyText.length).toBeGreaterThan(10);
  });

  // ═══ 场景: 导出 Skill 分享给同行: 导出 Skill 分享给同行 → 导出操作成功执行 [🟢🟢] ═══
  test('[32] 导出 Skill 分享给同行', async () => {
    // 触发: 导出 Skill 分享给同行
    // 预期: 导出操作成功执行
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证 Skill 卡片/项目列表
    const cards = page.locator('[data-testid="skill-card"], [data-testid="project-row"]');
    const cardCount = await cards.count();
    expect(cardCount).toBeGreaterThanOrEqual(0);
    if (cardCount > 0) await expect(cards.first()).toBeVisible();
  });

  // ═══ Spec: 条件分支: 若 检测到同名 Skill 已存在 → 弹出三选一对话框：① 覆盖现有（保留同名 Skill 的项目关联）② 保留两者（自动重命名新 Skill 为"名称 (1)"）③ 取消导入 [🟢🟢] ═══
  test('[33] 若 检测到同名 Skill 已存在', async () => {
    // 触发: 若 检测到同名 Skill 已存在
    // 预期: 弹出三选一对话框：① 覆盖现有（保留同名 Skill 的项目关联）② 保留两者（自动重命名新 Skill 为"名称 (1)"）③ 取消导入
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证弹窗出现
    const modal = page.locator('[data-testid="modal-overlay"]').first();
    const modalVisible = await modal.isVisible({ timeout: 3000 }).catch(() => false);
    if (modalVisible) {
      await expect(page.locator('[data-testid="modal-title"]').first()).toBeVisible();
      const confirmBtn = page.locator('[data-testid="modal-confirm"]').first();
      await expect(confirmBtn).toBeVisible();
    }
  });

  // ═══ Spec: 条件分支: 若 该 Skill 下还有未删除的项目 → 弹出警告"该 Skill 下有 N 个项目 [🟢🟢] ═══
  test('[34] 若 该 Skill 下还有未删除的项目', async () => {
    // 触发: 若 该 Skill 下还有未删除的项目
    // 预期: 弹出警告"该 Skill 下有 N 个项目
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证弹窗出现
    const modal = page.locator('[data-testid="modal-overlay"]').first();
    const modalVisible = await modal.isVisible({ timeout: 3000 }).catch(() => false);
    if (modalVisible) {
      await expect(page.locator('[data-testid="modal-title"]').first()).toBeVisible();
      const confirmBtn = page.locator('[data-testid="modal-confirm"]').first();
      await expect(confirmBtn).toBeVisible();
    }
  });

  // ═══ Spec: 条件分支: 若 原始路径已存在同名项目 → 弹出对话框"已存在同名项目 [🟢🟢] ═══
  test('[35] 若 原始路径已存在同名项目', async () => {
    // 触发: 若 原始路径已存在同名项目
    // 预期: 弹出对话框"已存在同名项目
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证弹窗出现
    const modal = page.locator('[data-testid="modal-overlay"]').first();
    const modalVisible = await modal.isVisible({ timeout: 3000 }).catch(() => false);
    if (modalVisible) {
      await expect(page.locator('[data-testid="modal-title"]').first()).toBeVisible();
      const confirmBtn = page.locator('[data-testid="modal-confirm"]').first();
      await expect(confirmBtn).toBeVisible();
    }
  });

  // ═══ Spec: 条件分支: 若 解析到的章节号在 `chapters/` 下无对应文件 → 章节行显示为灰色不可点击态 + ⚠ 图标 [🟢🟢] ═══
  test('[36] 若 解析到的章节号在 `chapters/` 下无对应文件', async () => {
    // 触发: 若 解析到的章节号在 `chapters/` 下无对应文件
    // 预期: 章节行显示为灰色不可点击态 + ⚠ 图标
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证章节行/文件项
    const rows = page.locator('[data-testid="chapter-row"], [data-testid="file-item"], [data-testid="stage-card"]');
    const rowCount = await rows.count();
    expect(rowCount).toBeGreaterThanOrEqual(0);
    if (rowCount > 0) await expect(rows.first()).toBeVisible();
  });

  // ═══ Spec: 条件分支: 若 解析出的章节数 ≠ `chapters/` 下实际 .md 文件数 → 视图顶部显示窄条警告"章节索引与文件数不一致" [🟢🟢] ═══
  test('[37] 若 解析出的章节数 ≠ `chapters/` 下实际 .md 文件数', async () => {
    // 触发: 若 解析出的章节数 ≠ `chapters/` 下实际 .md 文件数
    // 预期: 视图顶部显示窄条警告"章节索引与文件数不一致"
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证章节行/文件项
    const rows = page.locator('[data-testid="chapter-row"], [data-testid="file-item"], [data-testid="stage-card"]');
    const rowCount = await rows.count();
    expect(rowCount).toBeGreaterThanOrEqual(0);
    if (rowCount > 0) await expect(rows.first()).toBeVisible();
  });

  // ═══ Spec: 条件分支: 若 章节文件存在且为空 → 新建标签页加载文件 + **自动触发 AI** 生成该章节 [🟢🟢] ═══
  test('[38] 若 章节文件存在且为空', async () => {
    // 触发: 若 章节文件存在且为空
    // 预期: 新建标签页加载文件 + **自动触发 AI** 生成该章节
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证标签页
    const tabs = page.locator('[data-testid="tab"]');
    const tabCount = await tabs.count();
    expect(tabCount).toBeGreaterThanOrEqual(0);
    if (tabCount > 0) await expect(tabs.first()).toBeVisible();
  });

  // ═══ Spec: 条件分支: 若 章节文件已有内容 → 仅加载文件到编辑区 [🟢🟢] ═══
  test('[39] 若 章节文件已有内容', async () => {
    // 触发: 若 章节文件已有内容
    // 预期: 仅加载文件到编辑区
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证标签页
    const tabs = page.locator('[data-testid="tab"]');
    const tabCount = await tabs.count();
    expect(tabCount).toBeGreaterThanOrEqual(0);
    if (tabCount > 0) await expect(tabs.first()).toBeVisible();
  });

  // ═══ Spec: 条件分支: 若 项目目录已存在 `未命名.md` → 自动命名为 `未命名-1.md`、`未命名-2.md`... [🟢🟢] ═══
  test('[40] 若 项目目录已存在 `未命名.md`', async () => {
    // 触发: 若 项目目录已存在 `未命名.md`
    // 预期: 自动命名为 `未命名-1.md`、`未命名-2.md`...
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证 Skill 卡片/项目列表
    const cards = page.locator('[data-testid="skill-card"], [data-testid="project-row"]');
    const cardCount = await cards.count();
    expect(cardCount).toBeGreaterThanOrEqual(0);
    if (cardCount > 0) await expect(cards.first()).toBeVisible();
  });

  // ═══ Spec: 条件分支: 若 用户在预览期间修改了编辑区内容 → 点击应用时提示"编辑区内容已变更 [🟢🟢] ═══
  test('[41] 若 用户在预览期间修改了编辑区内容', async () => {
    // 触发: 若 用户在预览期间修改了编辑区内容
    // 预期: 点击应用时提示"编辑区内容已变更
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证输入区域可用
    const inputArea = page.locator('[data-testid="chat-input"], input:not([type="hidden"]), textarea, [contenteditable="true"]').first();
    const iaVisible = await inputArea.isVisible({ timeout: 3000 }).catch(() => false);
    if (iaVisible) {
      await expect(inputArea).toBeVisible();
      await expect(inputArea).toBeEnabled();
    }
  });

  // ═══ Spec: 条件分支: 若 该文件已在编辑区有打开的标签页 → 切换到已有标签页并聚焦 [🟢🟢] ═══
  test('[42] 若 该文件已在编辑区有打开的标签页', async () => {
    // 触发: 若 该文件已在编辑区有打开的标签页
    // 预期: 切换到已有标签页并聚焦
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证标签页
    const tabs = page.locator('[data-testid="tab"]');
    const tabCount = await tabs.count();
    expect(tabCount).toBeGreaterThanOrEqual(0);
    if (tabCount > 0) await expect(tabs.first()).toBeVisible();
  });

  // ═══ Spec: 条件分支: 若 内容非空） | → ✅（AI 完成后自动判定） | → ✅（保持） | [🟢🟢] ═══
  test('[43] 若 内容非空） |', async () => {
    // 触发: 若 内容非空） |
    // 预期: ✅（AI 完成后自动判定） | → ✅（保持） |
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证 AI 对话区
    const chatBody = page.locator('[data-testid="chat-body"]').first();
    const chatVisible = await chatBody.isVisible({ timeout: 3000 }).catch(() => false);
    if (chatVisible) {
      await expect(chatBody).toBeVisible();
      const msgs = page.locator('[data-testid="ai-message"], [data-testid="user-message"]');
      expect(await msgs.count()).toBeGreaterThanOrEqual(0);
    }
  });

  // ═══ Spec: 条件分支: 若 文件已有内容）或 → ⏹（若文件为空） | → ✅（保持） | [🟢🟢] ═══
  test('[44] 若 文件已有内容）或', async () => {
    // 触发: 若 文件已有内容）或
    // 预期: ⏹（若文件为空） | → ✅（保持） |
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证章节行/文件项
    const rows = page.locator('[data-testid="chapter-row"], [data-testid="file-item"], [data-testid="stage-card"]');
    const rowCount = await rows.count();
    expect(rowCount).toBeGreaterThanOrEqual(0);
    if (rowCount > 0) await expect(rows.first()).toBeVisible();
  });

  // ═══ Spec: 条件分支: 若 引擎不变 → 直接切换模型 [🟢] ═══
  test('[45] 若 引擎不变', async () => {
    // 触发: 若 引擎不变
    // 预期: 直接切换模型
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证状态变化
    await page.waitForTimeout(500);
    const bodyText = await page.locator('body').innerText().catch(() => '');
    expect(bodyText.length).toBeGreaterThan(20);
  });

  // ═══ Spec: 条件分支: 若 引擎变化 → 将当前引擎的对话历史导出为通用格式（JSON Lines [🟢🟢] ═══
  test('[46] 若 引擎变化', async () => {
    // 触发: 若 引擎变化
    // 预期: 将当前引擎的对话历史导出为通用格式（JSON Lines
    
    // 通用操作: 尝试匹配 data-testid 元素
    await page.waitForTimeout(800);

    // 验证 AI 对话区
    const chatBody = page.locator('[data-testid="chat-body"]').first();
    const chatVisible = await chatBody.isVisible({ timeout: 3000 }).catch(() => false);
    if (chatVisible) {
      await expect(chatBody).toBeVisible();
      const msgs = page.locator('[data-testid="ai-message"], [data-testid="user-message"]');
      expect(await msgs.count()).toBeGreaterThanOrEqual(0);
    }
  });

});
