/**
 * token-gen.js — Design Token → CSS 自动生成器
 *
 * 从 DESIGN-TOKENS.md 自动生成：
 *   1. src/styles/tokens.css          — CSS 自定义属性
 *   2. tailwind.config 更新           — theme.extend 自动同步
 *   3. --fix 模式                     — 硬编码值 → token 引用替换
 *
 * 用法:
 *   node token-gen.js                          # 生成 CSS + 更新 Tailwind
 *   node token-gen.js --fix                    # 生成 + 修复代码中硬编码值
 *   node token-gen.js --check                  # 仅检查，报告违规
 *   node token-gen.js --output /path/to/tokens # 自定义输出路径
 *
 * 通用性: 仅依赖 DESIGN-TOKENS.md 格式，不绑定产品。换产品 → 换 DESIGN-TOKENS.md → 自动生成。
 */

const fs = require('fs');
const path = require('path');

// ── 解析器 ──

/**
 * 从 DESIGN-TOKENS.md 解析 CSS 变量块
 * 返回 { tokenName: cssValue } 映射
 */
function parseTokens(content) {
  const tokens = {
    colors: {},
    fonts: {},
    spacing: {},
    fontSize: {},
    borderRadius: {},
  };

  // 提取 CSS 块中的变量定义: --name: value;
  const cssBlockRx = /```css\n([\s\S]*?)```/g;
  let cssBlock;
  while ((cssBlock = cssBlockRx.exec(content)) !== null) {
    const cssContent = cssBlock[1];
    const varRx = /--([\w-]+)\s*:\s*([^;]+);/g;
    let varMatch;
    while ((varMatch = varRx.exec(cssContent)) !== null) {
      const name = varMatch[1].trim();
      const value = varMatch[2].trim();

      // 分类
      if (name.startsWith('bg-') || name === 'accent' || name === 'accent-dim' ||
          name.startsWith('error-') || name.startsWith('warning-') || name.startsWith('success-') ||
          name.startsWith('border-') || name.startsWith('text-')) {
        tokens.colors[name] = value;
      } else if (name.startsWith('font-')) {
        tokens.fonts[name] = value;
      } else if (name.startsWith('spacing-') || name === 'gap' || name === 'padding') {
        tokens.spacing[name] = value;
      } else if (name.startsWith('font-size-') || name.startsWith('fs-')) {
        tokens.fontSize[name] = value;
      } else if (name.startsWith('radius-') || name.startsWith('br-')) {
        tokens.borderRadius[name] = value;
      }
    }
  }

  // 如果 CSS 块没提取到，尝试 Markdown 表格模式
  if (Object.keys(tokens.colors).length === 0) {
    parseTableTokens(content, tokens);
  }

  return tokens;
}

/**
 * 从 Markdown 表格中提取 token 映射
 * 格式: | `$token-name` | #HEX | 说明 |
 */
function parseTableTokens(content, tokens) {
  const tableRowRx = /\|\s*`?\$([\w-]+)`?\s*\|\s*(#[0-9A-Fa-f]{6,8}|#[0-9A-Fa-f]{3})(?:\s*\|[^|]*)?\|/g;
  let rowMatch;
  while ((rowMatch = tableRowRx.exec(content)) !== null) {
    const name = rowMatch[1].trim();
    const value = rowMatch[2].trim();
    // 分类同上
    if (name.startsWith('bg-') || name.includes('bg-') || name.startsWith('error-') || name.startsWith('warning-') || name.startsWith('text-') || name.startsWith('border-') || name === 'accent') {
      tokens.colors[name] = value;
    }
  }
}

// ── 生成器 ──

/**
 * 生成 CSS custom properties 文件
 */
function generateCSS(tokens, outputPath) {
  let css = '/* ⚠ AUTO-GENERATED by token-gen.js — DO NOT EDIT */\n';
  css += `/* 来源: DESIGN-TOKENS.md — ${new Date().toISOString()} */\n\n`;
  css += ':root {\n';

  // 颜色
  if (Object.keys(tokens.colors).length > 0) {
    css += '  /* ── 颜色 ── */\n';
    for (const [name, value] of Object.entries(tokens.colors)) {
      css += `  --${name}: ${value};\n`;
    }
    css += '\n';
  }

  // 字体
  if (Object.keys(tokens.fonts).length > 0) {
    css += '  /* ── 字体 ── */\n';
    for (const [name, value] of Object.entries(tokens.fonts)) {
      css += `  --${name}: ${value};\n`;
    }
    css += '\n';
  }

  // 间距
  if (Object.keys(tokens.spacing).length > 0) {
    css += '  /* ── 间距 ── */\n';
    for (const [name, value] of Object.entries(tokens.spacing)) {
      css += `  --${name}: ${value};\n`;
    }
    css += '\n';
  }

  css += '}\n';

  fs.writeFileSync(outputPath, css);
  console.log(`✅ tokens.css 已生成: ${outputPath} (${Object.keys(tokens.colors).length} 颜色 + ${Object.keys(tokens.fonts).length} 字体)`);
  return css;
}

/**
 * 生成 Tailwind v4 配置增量
 */
function generateTailwindConfig(tokens, outputPath) {
  const twColors = {};
  for (const [name, hex] of Object.entries(tokens.colors)) {
    // --bg-panel → panel
    const shortName = name.replace(/^(bg-|text-|border-|error-|warning-|success-)/, '');
    if (!twColors[shortName]) {
      twColors[shortName] = hex;
    }
    // 也保留完整名称
    twColors[name] = hex;
  }

  const twFonts = {};
  for (const [name, families] of Object.entries(tokens.fonts)) {
    const shortName = name.replace(/^font-/, '');
    twFonts[shortName] = families.split(',')[0].trim().replace(/'/g, '');
  }

  const config = {
    _note: 'AUTO-GENERATED by token-gen.js — 合并到 tailwind.config 的 theme.extend',
    theme: {
      extend: {
        colors: twColors,
        fontFamily: twFonts,
      },
    },
  };

  fs.writeFileSync(outputPath, JSON.stringify(config, null, 2));
  console.log(`✅ tailwind-tokens.json 已生成: ${outputPath}`);
  return config;
}

// ── 修复引擎 ──

/**
 * 扫描源代码中硬编码的设计值，替换为 token 引用
 */
function fixHardcodedValues(codeDir, tokens, options = {}) {
  const dryRun = options.dryRun || false;
  const exts = options.extensions || ['.tsx', '.ts', '.css'];
  const ignoreDirs = options.ignoreDirs || ['node_modules', 'out', 'dist', '.git'];

  // 构建 颜色 → token 的逆向映射
  const hexToToken = {};
  const hexToTailwind = {};
  for (const [name, hex] of Object.entries(tokens.colors)) {
    const normalized = hex.toUpperCase();
    if (!hexToToken[normalized]) {
      hexToToken[normalized] = `var(--${name})`;
      // 生成 Tailwind 类名
      const twClass = name.replace(/^bg-/, '').replace(/^text-/, '');
      hexToTailwind[normalized] = {
        bg: `bg-${twClass}`,
        text: `text-${twClass}`,
        border: `border-${twClass}`,
      };
    }
  }

  const allFiles = findFiles(codeDir, exts, ignoreDirs);
  const fixes = [];

  for (const file of allFiles) {
    let content = fs.readFileSync(file, 'utf-8');
    let modified = false;

    // 匹配硬编码的 hex 颜色
    const hexRx = /(?:fill|color|backgroundColor|background|stroke)=["'](#[0-9A-Fa-f]{6})["']/g;
    let match;
    while ((match = hexRx.exec(content)) !== null) {
      const hex = match[1].toUpperCase();
      if (hexToToken[hex]) {
        const original = match[0];
        const property = original.split('=')[0];
        const replacement = `${property}="${hexToTailwind[hex]?.bg || hexToToken[hex]}"`;
        fixes.push({ file, original: original.trim(), replacement, hex, token: hexToToken[hex] });
        if (!dryRun) {
          content = content.replace(original, replacement);
          modified = true;
        }
      }
    }

    if (modified && !dryRun) {
      fs.writeFileSync(file, content);
      console.log(`  🔧 ${path.relative(codeDir, file)}`);
    }
  }

  return fixes;
}

function findFiles(dir, exts, ignoreDirs) {
  const results = [];
  function walk(d, depth) {
    if (depth > 10) return;
    let entries;
    try { entries = fs.readdirSync(d, { withFileTypes: true }); }
    catch (_) { return; }
    for (const e of entries) {
      if (e.name.startsWith('.') || ignoreDirs.includes(e.name)) continue;
      const full = path.join(d, e.name);
      if (e.isDirectory()) walk(full, depth + 1);
      else if (exts.some(ext => e.name.endsWith(ext))) results.push(full);
    }
  }
  walk(dir, 0);
  return results;
}

// ── 主入口 ──

function main() {
  const args = process.argv.slice(2);
  const projectRoot = process.env.CLAUDE_PROJECT_DIR || process.cwd();
  const tokensPath = path.join(projectRoot, 'DESIGN-TOKENS.md');
  const outputDir = args.includes('--output') ? args[args.indexOf('--output') + 1] : path.join(projectRoot, 'do-zhou', 'src', 'styles');
  const fixMode = args.includes('--fix');
  const checkMode = args.includes('--check');
  const codeDir = args.includes('--code') ? args[args.indexOf('--code') + 1] : path.join(projectRoot, 'do-zhou', 'src');

  if (!fs.existsSync(tokensPath)) {
    console.error('🔴 DESIGN-TOKENS.md 不存在。无法生成 token。');
    process.exit(1);
  }

  const content = fs.readFileSync(tokensPath, 'utf-8');
  const tokens = parseTokens(content);

  console.log(`📊 解析到: ${Object.keys(tokens.colors).length} 颜色, ${Object.keys(tokens.fonts).length} 字体`);

  // 确保输出目录存在
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // 生成 CSS
  generateCSS(tokens, path.join(outputDir, 'tokens.css'));

  // 生成 Tailwind 配置
  generateTailwindConfig(tokens, path.join(projectRoot, '.claude', '.tailwind-tokens.json'));

  // 更新 .token-map.json
  const tokenMap = {};
  for (const [name, hex] of Object.entries(tokens.colors)) {
    const twClass = name.replace(/^bg-/, '').replace(/^text-/, '').replace(/^border-/, '');
    tokenMap[twClass] = { token: `$${name}`, hex, css: `var(--${name})` };
  }
  fs.writeFileSync(path.join(projectRoot, '.claude', '.token-map.json'), JSON.stringify(tokenMap, null, 2));
  console.log(`✅ .token-map.json 已更新: ${Object.keys(tokenMap).length} 个映射`);

  // 修复模式
  if (fixMode && fs.existsSync(codeDir)) {
    console.log('\n🔧 --fix 模式: 替换硬编码颜色...');
    const fixes = fixHardcodedValues(codeDir, tokens, { dryRun: false });
    console.log(`✅ 替换了 ${fixes.length} 处硬编码颜色`);
  } else if (checkMode && fs.existsSync(codeDir)) {
    console.log('\n🔍 --check 模式: 扫描硬编码颜色...');
    const fixes = fixHardcodedValues(codeDir, tokens, { dryRun: true });
    if (fixes.length > 0) {
      console.error(`❌ 发现 ${fixes.length} 处硬编码颜色:`);
      for (const f of fixes) {
        console.error(`  ${f.file}: ${f.original} → 应使用 ${f.token}`);
      }
      process.exit(1);
    } else {
      console.log('✅ 无硬编码颜色违例');
    }
  }
}

module.exports = { parseTokens, generateCSS, generateTailwindConfig, fixHardcodedValues };

if (require.main === module) {
  main();
}
